// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

type Finding struct {
	ID                int64  `json:"id"`
	RunID             string `json:"run_id"`
	RepoID            string `json:"repo_id"`
	Fingerprint       string `json:"fingerprint"`
	Scanner           string `json:"scanner"`
	Scanners          string `json:"scanners"`
	RuleID            string `json:"rule_id"`
	Aliases           string `json:"aliases"`
	Category          string `json:"category"`
	Severity          string `json:"severity"`
	Title             string `json:"title"`
	Message           string `json:"message"`
	LocationPath      string `json:"location_path"`
	LocationStartLine int64  `json:"location_start_line"`
	LocationEndLine   int64  `json:"location_end_line"`
	LocationSnippet   string `json:"location_snippet"`
	PackageName       string `json:"package_name"`
	PackageVersion    string `json:"package_version"`
	PackageEcosystem  string `json:"package_ecosystem"`
	PackagePurl       string `json:"package_purl"`
	FixedIn           string `json:"fixed_in"`
	Refs              string `json:"refs"`
	Status            string `json:"status"`
}

type FindingState struct {
	RepoID      string `json:"repo_id"`
	Fingerprint string `json:"fingerprint"`
	Status      string `json:"status"`
	Severity    string `json:"severity"`
	Category    string `json:"category"`
	Title       string `json:"title"`
	Scanners    string `json:"scanners"`
	FirstSeenAt string `json:"first_seen_at"`
	LastSeenAt  string `json:"last_seen_at"`
	FirstRun    string `json:"first_run"`
	LastRun     string `json:"last_run"`
	FixedAt     string `json:"fixed_at"`
	FixedRun    string `json:"fixed_run"`
	Occurrences int64  `json:"occurrences"`
	Regressions int64  `json:"regressions"`
}

type Repo struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Path        string `json:"path"`
	FormerPaths string `json:"former_paths"`
	Origin      string `json:"origin"`
	FirstRunAt  string `json:"first_run_at"`
	LastRunAt   string `json:"last_run_at"`
	LastRunID   string `json:"last_run_id"`
}

type Run struct {
	ID          string `json:"id"`
	RepoID      string `json:"repo_id"`
	PrevRunID   string `json:"prev_run_id"`
	StartedAt   string `json:"started_at"`
	FinishedAt  string `json:"finished_at"`
	DurationMs  int64  `json:"duration_ms"`
	ToolName    string `json:"tool_name"`
	ToolVersion string `json:"tool_version"`
	VcsOrigin   string `json:"vcs_origin"`
	VcsBranch   string `json:"vcs_branch"`
	VcsCommit   string `json:"vcs_commit"`
	Scanners    string `json:"scanners"`
	ScopeHash   string `json:"scope_hash"`
	Counts      string `json:"counts"`
	Delta       string `json:"delta"`
	Unreadable  int64  `json:"unreadable"`
	Problem     string `json:"problem"`
	Document    string `json:"document"`
}
