// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"strings"
)

const deleteFindingStatesByRepo = `-- name: DeleteFindingStatesByRepo :exec
DELETE FROM finding_states WHERE repo_id = ?
`

func (q *Queries) DeleteFindingStatesByRepo(ctx context.Context, repoID string) error {
	_, err := q.db.ExecContext(ctx, deleteFindingStatesByRepo, repoID)
	return err
}

const deleteRepo = `-- name: DeleteRepo :exec
DELETE FROM repos WHERE id = ?
`

func (q *Queries) DeleteRepo(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRepo, id)
	return err
}

const deleteRuns = `-- name: DeleteRuns :exec
DELETE FROM runs WHERE repo_id = ? AND id IN (/*SLICE:ids*/?)
`

type DeleteRunsParams struct {
	RepoID string   `json:"repo_id"`
	Ids    []string `json:"ids"`
}

func (q *Queries) DeleteRuns(ctx context.Context, arg DeleteRunsParams) error {
	query := deleteRuns
	var queryParams []interface{}
	queryParams = append(queryParams, arg.RepoID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const getNewestRunID = `-- name: GetNewestRunID :one
SELECT id FROM runs
WHERE repo_id = ?
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetNewestRunID(ctx context.Context, repoID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getNewestRunID, repoID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getRepo = `-- name: GetRepo :one
SELECT id, name, path, former_paths, origin, first_run_at, last_run_at, last_run_id
FROM repos
WHERE id = ?
`

func (q *Queries) GetRepo(ctx context.Context, id string) (Repo, error) {
	row := q.db.QueryRowContext(ctx, getRepo, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.FormerPaths,
		&i.Origin,
		&i.FirstRunAt,
		&i.LastRunAt,
		&i.LastRunID,
	)
	return i, err
}

const getRepoByFormerPath = `-- name: GetRepoByFormerPath :one
SELECT id, name, path, former_paths, origin, first_run_at, last_run_at, last_run_id
FROM repos
WHERE former_paths LIKE '%' || ? || '%'
`

func (q *Queries) GetRepoByFormerPath(ctx context.Context, dollar_1 sql.NullString) (Repo, error) {
	row := q.db.QueryRowContext(ctx, getRepoByFormerPath, dollar_1)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.FormerPaths,
		&i.Origin,
		&i.FirstRunAt,
		&i.LastRunAt,
		&i.LastRunID,
	)
	return i, err
}

const getRepoByPath = `-- name: GetRepoByPath :one
SELECT id, name, path, former_paths, origin, first_run_at, last_run_at, last_run_id
FROM repos
WHERE path = ?
`

func (q *Queries) GetRepoByPath(ctx context.Context, path string) (Repo, error) {
	row := q.db.QueryRowContext(ctx, getRepoByPath, path)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.FormerPaths,
		&i.Origin,
		&i.FirstRunAt,
		&i.LastRunAt,
		&i.LastRunID,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, repo_id, prev_run_id, started_at, finished_at, duration_ms,
       tool_name, tool_version, vcs_origin, vcs_branch, vcs_commit,
       scanners, scope_hash, counts, delta, unreadable, problem, document
FROM runs
WHERE repo_id = ? AND id = ?
`

type GetRunParams struct {
	RepoID string `json:"repo_id"`
	ID     string `json:"id"`
}

func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, arg.RepoID, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.PrevRunID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.ToolName,
		&i.ToolVersion,
		&i.VcsOrigin,
		&i.VcsBranch,
		&i.VcsCommit,
		&i.Scanners,
		&i.ScopeHash,
		&i.Counts,
		&i.Delta,
		&i.Unreadable,
		&i.Problem,
		&i.Document,
	)
	return i, err
}

const insertFinding = `-- name: InsertFinding :exec
INSERT INTO findings (
    run_id, repo_id, fingerprint, scanner, scanners, rule_id, aliases,
    category, severity, title, message, location_path, location_start_line,
    location_end_line, location_snippet, package_name, package_version,
    package_ecosystem, package_purl, fixed_in, refs, status
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertFindingParams struct {
	RunID             string `json:"run_id"`
	RepoID            string `json:"repo_id"`
	Fingerprint       string `json:"fingerprint"`
	Scanner           string `json:"scanner"`
	Scanners          string `json:"scanners"`
	RuleID            string `json:"rule_id"`
	Aliases           string `json:"aliases"`
	Category          string `json:"category"`
	Severity          string `json:"severity"`
	Title             string `json:"title"`
	Message           string `json:"message"`
	LocationPath      string `json:"location_path"`
	LocationStartLine int64  `json:"location_start_line"`
	LocationEndLine   int64  `json:"location_end_line"`
	LocationSnippet   string `json:"location_snippet"`
	PackageName       string `json:"package_name"`
	PackageVersion    string `json:"package_version"`
	PackageEcosystem  string `json:"package_ecosystem"`
	PackagePurl       string `json:"package_purl"`
	FixedIn           string `json:"fixed_in"`
	Refs              string `json:"refs"`
	Status            string `json:"status"`
}

func (q *Queries) InsertFinding(ctx context.Context, arg InsertFindingParams) error {
	_, err := q.db.ExecContext(ctx, insertFinding,
		arg.RunID,
		arg.RepoID,
		arg.Fingerprint,
		arg.Scanner,
		arg.Scanners,
		arg.RuleID,
		arg.Aliases,
		arg.Category,
		arg.Severity,
		arg.Title,
		arg.Message,
		arg.LocationPath,
		arg.LocationStartLine,
		arg.LocationEndLine,
		arg.LocationSnippet,
		arg.PackageName,
		arg.PackageVersion,
		arg.PackageEcosystem,
		arg.PackagePurl,
		arg.FixedIn,
		arg.Refs,
		arg.Status,
	)
	return err
}

const insertRun = `-- name: InsertRun :exec
INSERT INTO runs (
    id, repo_id, prev_run_id, started_at, finished_at, duration_ms,
    tool_name, tool_version, vcs_origin, vcs_branch, vcs_commit,
    scanners, scope_hash, counts, delta, unreadable, problem, document
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertRunParams struct {
	ID          string `json:"id"`
	RepoID      string `json:"repo_id"`
	PrevRunID   string `json:"prev_run_id"`
	StartedAt   string `json:"started_at"`
	FinishedAt  string `json:"finished_at"`
	DurationMs  int64  `json:"duration_ms"`
	ToolName    string `json:"tool_name"`
	ToolVersion string `json:"tool_version"`
	VcsOrigin   string `json:"vcs_origin"`
	VcsBranch   string `json:"vcs_branch"`
	VcsCommit   string `json:"vcs_commit"`
	Scanners    string `json:"scanners"`
	ScopeHash   string `json:"scope_hash"`
	Counts      string `json:"counts"`
	Delta       string `json:"delta"`
	Unreadable  int64  `json:"unreadable"`
	Problem     string `json:"problem"`
	Document    string `json:"document"`
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) error {
	_, err := q.db.ExecContext(ctx, insertRun,
		arg.ID,
		arg.RepoID,
		arg.PrevRunID,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationMs,
		arg.ToolName,
		arg.ToolVersion,
		arg.VcsOrigin,
		arg.VcsBranch,
		arg.VcsCommit,
		arg.Scanners,
		arg.ScopeHash,
		arg.Counts,
		arg.Delta,
		arg.Unreadable,
		arg.Problem,
		arg.Document,
	)
	return err
}

const listFindingStates = `-- name: ListFindingStates :many
SELECT repo_id, fingerprint, status, severity, category, title, scanners,
       first_seen_at, last_seen_at, first_run, last_run, fixed_at, fixed_run,
       occurrences, regressions
FROM finding_states
WHERE repo_id = ?
`

func (q *Queries) ListFindingStates(ctx context.Context, repoID string) ([]FindingState, error) {
	rows, err := q.db.QueryContext(ctx, listFindingStates, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindingState{}
	for rows.Next() {
		var i FindingState
		if err := rows.Scan(
			&i.RepoID,
			&i.Fingerprint,
			&i.Status,
			&i.Severity,
			&i.Category,
			&i.Title,
			&i.Scanners,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.FirstRun,
			&i.LastRun,
			&i.FixedAt,
			&i.FixedRun,
			&i.Occurrences,
			&i.Regressions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsByRun = `-- name: ListFindingsByRun :many
SELECT id, run_id, repo_id, fingerprint, scanner, scanners, rule_id, aliases,
       category, severity, title, message, location_path, location_start_line,
       location_end_line, location_snippet, package_name, package_version,
       package_ecosystem, package_purl, fixed_in, refs, status
FROM findings
WHERE run_id = ?
ORDER BY id ASC
`

func (q *Queries) ListFindingsByRun(ctx context.Context, runID string) ([]Finding, error) {
	rows, err := q.db.QueryContext(ctx, listFindingsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Finding{}
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.RepoID,
			&i.Fingerprint,
			&i.Scanner,
			&i.Scanners,
			&i.RuleID,
			&i.Aliases,
			&i.Category,
			&i.Severity,
			&i.Title,
			&i.Message,
			&i.LocationPath,
			&i.LocationStartLine,
			&i.LocationEndLine,
			&i.LocationSnippet,
			&i.PackageName,
			&i.PackageVersion,
			&i.PackageEcosystem,
			&i.PackagePurl,
			&i.FixedIn,
			&i.Refs,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoIDs = `-- name: ListRepoIDs :many
SELECT id FROM repos
`

func (q *Queries) ListRepoIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRepoIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepos = `-- name: ListRepos :many
SELECT id, name, path, former_paths, origin, first_run_at, last_run_at, last_run_id
FROM repos
ORDER BY last_run_at DESC, id ASC
`

func (q *Queries) ListRepos(ctx context.Context) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repo{}
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.FormerPaths,
			&i.Origin,
			&i.FirstRunAt,
			&i.LastRunAt,
			&i.LastRunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByRepo = `-- name: ListRunsByRepo :many
SELECT id, repo_id, prev_run_id, started_at, finished_at, duration_ms,
       tool_name, tool_version, vcs_origin, vcs_branch, vcs_commit,
       scanners, scope_hash, counts, delta, unreadable, problem, document
FROM runs
WHERE repo_id = ?
ORDER BY id ASC
`

func (q *Queries) ListRunsByRepo(ctx context.Context, repoID string) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.PrevRunID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ToolName,
			&i.ToolVersion,
			&i.VcsOrigin,
			&i.VcsBranch,
			&i.VcsCommit,
			&i.Scanners,
			&i.ScopeHash,
			&i.Counts,
			&i.Delta,
			&i.Unreadable,
			&i.Problem,
			&i.Document,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunDerived = `-- name: UpdateRunDerived :exec
UPDATE runs SET
    prev_run_id = ?,
    counts = ?,
    delta = ?,
    unreadable = ?,
    problem = ?,
    document = ?
WHERE repo_id = ? AND id = ?
`

type UpdateRunDerivedParams struct {
	PrevRunID  string `json:"prev_run_id"`
	Counts     string `json:"counts"`
	Delta      string `json:"delta"`
	Unreadable int64  `json:"unreadable"`
	Problem    string `json:"problem"`
	Document   string `json:"document"`
	RepoID     string `json:"repo_id"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateRunDerived(ctx context.Context, arg UpdateRunDerivedParams) error {
	_, err := q.db.ExecContext(ctx, updateRunDerived,
		arg.PrevRunID,
		arg.Counts,
		arg.Delta,
		arg.Unreadable,
		arg.Problem,
		arg.Document,
		arg.RepoID,
		arg.ID,
	)
	return err
}

const upsertFindingState = `-- name: UpsertFindingState :exec
INSERT INTO finding_states (
    repo_id, fingerprint, status, severity, category, title, scanners,
    first_seen_at, last_seen_at, first_run, last_run, fixed_at, fixed_run,
    occurrences, regressions
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(repo_id, fingerprint) DO UPDATE SET
    status = excluded.status,
    severity = excluded.severity,
    category = excluded.category,
    title = excluded.title,
    scanners = excluded.scanners,
    first_seen_at = excluded.first_seen_at,
    last_seen_at = excluded.last_seen_at,
    first_run = excluded.first_run,
    last_run = excluded.last_run,
    fixed_at = excluded.fixed_at,
    fixed_run = excluded.fixed_run,
    occurrences = excluded.occurrences,
    regressions = excluded.regressions
`

type UpsertFindingStateParams struct {
	RepoID      string `json:"repo_id"`
	Fingerprint string `json:"fingerprint"`
	Status      string `json:"status"`
	Severity    string `json:"severity"`
	Category    string `json:"category"`
	Title       string `json:"title"`
	Scanners    string `json:"scanners"`
	FirstSeenAt string `json:"first_seen_at"`
	LastSeenAt  string `json:"last_seen_at"`
	FirstRun    string `json:"first_run"`
	LastRun     string `json:"last_run"`
	FixedAt     string `json:"fixed_at"`
	FixedRun    string `json:"fixed_run"`
	Occurrences int64  `json:"occurrences"`
	Regressions int64  `json:"regressions"`
}

func (q *Queries) UpsertFindingState(ctx context.Context, arg UpsertFindingStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertFindingState,
		arg.RepoID,
		arg.Fingerprint,
		arg.Status,
		arg.Severity,
		arg.Category,
		arg.Title,
		arg.Scanners,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.FirstRun,
		arg.LastRun,
		arg.FixedAt,
		arg.FixedRun,
		arg.Occurrences,
		arg.Regressions,
	)
	return err
}

const upsertRepo = `-- name: UpsertRepo :exec
INSERT INTO repos (id, name, path, former_paths, origin, first_run_at, last_run_at, last_run_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    path = excluded.path,
    former_paths = excluded.former_paths,
    origin = excluded.origin,
    first_run_at = excluded.first_run_at,
    last_run_at = excluded.last_run_at,
    last_run_id = excluded.last_run_id
`

type UpsertRepoParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Path        string `json:"path"`
	FormerPaths string `json:"former_paths"`
	Origin      string `json:"origin"`
	FirstRunAt  string `json:"first_run_at"`
	LastRunAt   string `json:"last_run_at"`
	LastRunID   string `json:"last_run_id"`
}

func (q *Queries) UpsertRepo(ctx context.Context, arg UpsertRepoParams) error {
	_, err := q.db.ExecContext(ctx, upsertRepo,
		arg.ID,
		arg.Name,
		arg.Path,
		arg.FormerPaths,
		arg.Origin,
		arg.FirstRunAt,
		arg.LastRunAt,
		arg.LastRunID,
	)
	return err
}
