# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pindrop < Formula
  desc "Find, prioritize, and track security issues in your code"
  homepage "https://github.com/AnimeshRy/pindrop"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AnimeshRy/pindrop/releases/download/v0.2.1/pindrop_0.2.1_darwin_amd64.tar.gz"
      sha256 "041b673ee03acb777d4ed720ae70a37cb0a5249efc1df370677d91afd3dd6ca2"

      define_method(:install) do
        bin.install "pindrop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AnimeshRy/pindrop/releases/download/v0.2.1/pindrop_0.2.1_darwin_arm64.tar.gz"
      sha256 "85bfa9e9627353e3acd37f323598bc7f0ab2aeaf0eacfa9d6d915522cd6a135e"

      define_method(:install) do
        bin.install "pindrop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnimeshRy/pindrop/releases/download/v0.2.1/pindrop_0.2.1_linux_amd64.tar.gz"
      sha256 "d38f219b116f54fc59795ed2b1fc06fa9218d6895ca93ff56097938823b40faf"
      define_method(:install) do
        bin.install "pindrop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnimeshRy/pindrop/releases/download/v0.2.1/pindrop_0.2.1_linux_arm64.tar.gz"
      sha256 "a95e3986185936a4942b12f85a2cbd01fba4633b2f46d9286391f73bb0772ec7"
      define_method(:install) do
        bin.install "pindrop"
      end
    end
  end

  test do
    system "#{bin}/pindrop", "version"
  end
end
