# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pindrop < Formula
  desc "Find, prioritize, and track security issues in your code"
  homepage "https://github.com/AnimeshRy/pindrop"
  version "0.2.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AnimeshRy/pindrop/releases/download/v0.2.3/pindrop_0.2.3_darwin_amd64.tar.gz"
      sha256 "6c4c5836b2664b507b8082450ca4a5029481d1f13117bb322c048c0e611bb757"

      define_method(:install) do
        bin.install "pindrop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AnimeshRy/pindrop/releases/download/v0.2.3/pindrop_0.2.3_darwin_arm64.tar.gz"
      sha256 "178b8edf28d45b9582ae1985ab73e9ecb5f2a67f879cadb73d775f1d9f89a374"

      define_method(:install) do
        bin.install "pindrop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnimeshRy/pindrop/releases/download/v0.2.3/pindrop_0.2.3_linux_amd64.tar.gz"
      sha256 "6fbe5b21a64b064c32087d47c7f01a2802c62ac8645343dbd73389f800546bcf"
      define_method(:install) do
        bin.install "pindrop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnimeshRy/pindrop/releases/download/v0.2.3/pindrop_0.2.3_linux_arm64.tar.gz"
      sha256 "6adc33ff2feb1adce9cf42447c1e03744f407b94c50aca823ae17a4753ab14b0"
      define_method(:install) do
        bin.install "pindrop"
      end
    end
  end

  test do
    system "#{bin}/pindrop", "version"
  end
end
