// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Finding struct {
	ID                int64       `json:"id"`
	OrgID             pgtype.UUID `json:"org_id"`
	RepoID            pgtype.UUID `json:"repo_id"`
	RunID             pgtype.UUID `json:"run_id"`
	Fingerprint       string      `json:"fingerprint"`
	Scanner           string      `json:"scanner"`
	Scanners          []byte      `json:"scanners"`
	RuleID            string      `json:"rule_id"`
	Aliases           []byte      `json:"aliases"`
	Category          string      `json:"category"`
	Severity          string      `json:"severity"`
	Title             string      `json:"title"`
	Message           string      `json:"message"`
	LocationPath      string      `json:"location_path"`
	LocationStartLine int32       `json:"location_start_line"`
	LocationEndLine   int32       `json:"location_end_line"`
	LocationSnippet   string      `json:"location_snippet"`
	PackageName       string      `json:"package_name"`
	PackageVersion    string      `json:"package_version"`
	PackageEcosystem  string      `json:"package_ecosystem"`
	PackagePurl       string      `json:"package_purl"`
	FixedIn           string      `json:"fixed_in"`
	Refs              []byte      `json:"refs"`
	Status            string      `json:"status"`
}

type FindingState struct {
	OrgID       pgtype.UUID        `json:"org_id"`
	RepoID      pgtype.UUID        `json:"repo_id"`
	Fingerprint string             `json:"fingerprint"`
	Status      string             `json:"status"`
	Severity    string             `json:"severity"`
	Category    string             `json:"category"`
	Title       string             `json:"title"`
	Scanners    []byte             `json:"scanners"`
	FirstSeenAt pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	FirstRun    string             `json:"first_run"`
	LastRun     string             `json:"last_run"`
	FixedAt     pgtype.Timestamptz `json:"fixed_at"`
	FixedRun    string             `json:"fixed_run"`
	Occurrences int32              `json:"occurrences"`
	Regressions int32              `json:"regressions"`
}

type Org struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OrgMember struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

type Repo struct {
	ID            pgtype.UUID        `json:"id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	Name          string             `json:"name"`
	Origin        string             `json:"origin"`
	LastRunID     string             `json:"last_run_id"`
	FirstSyncedAt pgtype.Timestamptz `json:"first_synced_at"`
	LastSyncedAt  pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type RepoLink struct {
	ID            pgtype.UUID        `json:"id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	RepoID        pgtype.UUID        `json:"repo_id"`
	Source        string             `json:"source"`
	ExternalID    string             `json:"external_id"`
	Path          string             `json:"path"`
	FormerPaths   []byte             `json:"former_paths"`
	Metadata      []byte             `json:"metadata"`
	FirstSyncedAt pgtype.Timestamptz `json:"first_synced_at"`
	LastSyncedAt  pgtype.Timestamptz `json:"last_synced_at"`
}

type Run struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	RepoID      pgtype.UUID        `json:"repo_id"`
	Source      string             `json:"source"`
	ClientRunID string             `json:"client_run_id"`
	PrevRunID   string             `json:"prev_run_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	DurationMs  int64              `json:"duration_ms"`
	ToolName    string             `json:"tool_name"`
	ToolVersion string             `json:"tool_version"`
	VcsOrigin   string             `json:"vcs_origin"`
	VcsBranch   string             `json:"vcs_branch"`
	VcsCommit   string             `json:"vcs_commit"`
	Scanners    []byte             `json:"scanners"`
	ScopeHash   string             `json:"scope_hash"`
	Counts      []byte             `json:"counts"`
	Delta       []byte             `json:"delta"`
	Unreadable  bool               `json:"unreadable"`
	Problem     string             `json:"problem"`
	Document    []byte             `json:"document"`
	SyncedAt    pgtype.Timestamptz `json:"synced_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
