// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOrgMember = `-- name: AddOrgMember :exec
INSERT INTO org_members (org_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddOrgMemberParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) AddOrgMember(ctx context.Context, arg AddOrgMemberParams) error {
	_, err := q.db.Exec(ctx, addOrgMember, arg.OrgID, arg.UserID, arg.Role)
	return err
}

const countFindingsByRunFiltered = `-- name: CountFindingsByRunFiltered :one
SELECT COUNT(*)::bigint AS count
FROM findings f
WHERE f.org_id = $1 AND f.run_id = $2
  AND ($3 = '' OR f.severity = $3)
  AND ($4 = '' OR f.category = $4)
  AND ($5 = '' OR f.status = $5)
  AND ($6 = '' OR (
    f.title ILIKE '%' || $6 || '%'
    OR f.message ILIKE '%' || $6 || '%'
    OR f.rule_id ILIKE '%' || $6 || '%'
    OR f.location_path ILIKE '%' || $6 || '%'
  ))
`

type CountFindingsByRunFilteredParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	RunID    pgtype.UUID `json:"run_id"`
	Severity interface{} `json:"severity"`
	Category interface{} `json:"category"`
	Status   interface{} `json:"status"`
	Search   interface{} `json:"search"`
}

func (q *Queries) CountFindingsByRunFiltered(ctx context.Context, arg CountFindingsByRunFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFindingsByRunFiltered,
		arg.OrgID,
		arg.RunID,
		arg.Severity,
		arg.Category,
		arg.Status,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenFindingsByRepo = `-- name: CountOpenFindingsByRepo :one
SELECT COUNT(*)::bigint AS count
FROM finding_states
WHERE org_id = $1 AND repo_id = $2 AND status IN ('new', 'open', 'regressed')
`

type CountOpenFindingsByRepoParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	RepoID pgtype.UUID `json:"repo_id"`
}

func (q *Queries) CountOpenFindingsByRepo(ctx context.Context, arg CountOpenFindingsByRepoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenFindingsByRepo, arg.OrgID, arg.RepoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenFindingsBySeverityByRepo = `-- name: CountOpenFindingsBySeverityByRepo :many
SELECT severity, COUNT(*)::bigint AS count
FROM finding_states
WHERE org_id = $1 AND repo_id = $2 AND status IN ('new', 'open', 'regressed')
GROUP BY severity
`

type CountOpenFindingsBySeverityByRepoParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	RepoID pgtype.UUID `json:"repo_id"`
}

type CountOpenFindingsBySeverityByRepoRow struct {
	Severity string `json:"severity"`
	Count    int64  `json:"count"`
}

func (q *Queries) CountOpenFindingsBySeverityByRepo(ctx context.Context, arg CountOpenFindingsBySeverityByRepoParams) ([]CountOpenFindingsBySeverityByRepoRow, error) {
	rows, err := q.db.Query(ctx, countOpenFindingsBySeverityByRepo, arg.OrgID, arg.RepoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountOpenFindingsBySeverityByRepoRow{}
	for rows.Next() {
		var i CountOpenFindingsBySeverityByRepoRow
		if err := rows.Scan(&i.Severity, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countRunsByRepo = `-- name: CountRunsByRepo :one
SELECT COUNT(*)::bigint AS count
FROM runs
WHERE org_id = $1 AND repo_id = $2
`

type CountRunsByRepoParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	RepoID pgtype.UUID `json:"repo_id"`
}

func (q *Queries) CountRunsByRepo(ctx context.Context, arg CountRunsByRepoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRunsByRepo, arg.OrgID, arg.RepoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrg = `-- name: CreateOrg :one
INSERT INTO orgs (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateOrg(ctx context.Context, name string) (Org, error) {
	row := q.db.QueryRow(ctx, createOrg, name)
	var i Org
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteFindingStatesByRepo = `-- name: DeleteFindingStatesByRepo :exec
DELETE FROM finding_states
WHERE org_id = $1 AND repo_id = $2
`

type DeleteFindingStatesByRepoParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	RepoID pgtype.UUID `json:"repo_id"`
}

func (q *Queries) DeleteFindingStatesByRepo(ctx context.Context, arg DeleteFindingStatesByRepoParams) error {
	_, err := q.db.Exec(ctx, deleteFindingStatesByRepo, arg.OrgID, arg.RepoID)
	return err
}

const deleteFindingsByRun = `-- name: DeleteFindingsByRun :exec
DELETE FROM findings
WHERE org_id = $1 AND run_id = $2
`

type DeleteFindingsByRunParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	RunID pgtype.UUID `json:"run_id"`
}

func (q *Queries) DeleteFindingsByRun(ctx context.Context, arg DeleteFindingsByRunParams) error {
	_, err := q.db.Exec(ctx, deleteFindingsByRun, arg.OrgID, arg.RunID)
	return err
}

const getPersonalOrgForUser = `-- name: GetPersonalOrgForUser :one
SELECT o.id, o.name, o.created_at
FROM orgs o
JOIN org_members m ON m.org_id = o.id
WHERE m.user_id = $1 AND m.role = 'owner'
ORDER BY o.created_at ASC
LIMIT 1
`

func (q *Queries) GetPersonalOrgForUser(ctx context.Context, userID pgtype.UUID) (Org, error) {
	row := q.db.QueryRow(ctx, getPersonalOrgForUser, userID)
	var i Org
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getRepoByID = `-- name: GetRepoByID :one
SELECT id, org_id, name, origin, last_run_id, first_synced_at, last_synced_at, created_at
FROM repos
WHERE org_id = $1 AND id = $2
`

type GetRepoByIDParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) GetRepoByID(ctx context.Context, arg GetRepoByIDParams) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoByID, arg.OrgID, arg.ID)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Origin,
		&i.LastRunID,
		&i.FirstSyncedAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRepoByOrigin = `-- name: GetRepoByOrigin :one
SELECT id, org_id, name, origin, last_run_id, first_synced_at, last_synced_at, created_at
FROM repos
WHERE org_id = $1 AND origin = $2 AND origin <> ''
LIMIT 1
`

type GetRepoByOriginParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	Origin string      `json:"origin"`
}

func (q *Queries) GetRepoByOrigin(ctx context.Context, arg GetRepoByOriginParams) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoByOrigin, arg.OrgID, arg.Origin)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Origin,
		&i.LastRunID,
		&i.FirstSyncedAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRepoLinkByExternal = `-- name: GetRepoLinkByExternal :one
SELECT id, org_id, repo_id, source, external_id, path, former_paths, metadata,
       first_synced_at, last_synced_at
FROM repo_links
WHERE org_id = $1 AND source = $2 AND external_id = $3
`

type GetRepoLinkByExternalParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	Source     string      `json:"source"`
	ExternalID string      `json:"external_id"`
}

func (q *Queries) GetRepoLinkByExternal(ctx context.Context, arg GetRepoLinkByExternalParams) (RepoLink, error) {
	row := q.db.QueryRow(ctx, getRepoLinkByExternal, arg.OrgID, arg.Source, arg.ExternalID)
	var i RepoLink
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RepoID,
		&i.Source,
		&i.ExternalID,
		&i.Path,
		&i.FormerPaths,
		&i.Metadata,
		&i.FirstSyncedAt,
		&i.LastSyncedAt,
	)
	return i, err
}

const getRunByClientID = `-- name: GetRunByClientID :one
SELECT id, org_id, repo_id, source, client_run_id, prev_run_id, started_at, finished_at,
       duration_ms, tool_name, tool_version, vcs_origin, vcs_branch, vcs_commit,
       scanners, scope_hash, counts, delta, unreadable, problem, document, synced_at
FROM runs
WHERE repo_id = $1 AND client_run_id = $2
`

type GetRunByClientIDParams struct {
	RepoID      pgtype.UUID `json:"repo_id"`
	ClientRunID string      `json:"client_run_id"`
}

func (q *Queries) GetRunByClientID(ctx context.Context, arg GetRunByClientIDParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRunByClientID, arg.RepoID, arg.ClientRunID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RepoID,
		&i.Source,
		&i.ClientRunID,
		&i.PrevRunID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.ToolName,
		&i.ToolVersion,
		&i.VcsOrigin,
		&i.VcsBranch,
		&i.VcsCommit,
		&i.Scanners,
		&i.ScopeHash,
		&i.Counts,
		&i.Delta,
		&i.Unreadable,
		&i.Problem,
		&i.Document,
		&i.SyncedAt,
	)
	return i, err
}

const getRunByID = `-- name: GetRunByID :one
SELECT id, org_id, repo_id, source, client_run_id, prev_run_id, started_at, finished_at,
       duration_ms, tool_name, tool_version, vcs_origin, vcs_branch, vcs_commit,
       scanners, scope_hash, counts, delta, unreadable, problem, document, synced_at
FROM runs
WHERE org_id = $1 AND repo_id = $2 AND id = $3
`

type GetRunByIDParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	RepoID pgtype.UUID `json:"repo_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) GetRunByID(ctx context.Context, arg GetRunByIDParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRunByID, arg.OrgID, arg.RepoID, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RepoID,
		&i.Source,
		&i.ClientRunID,
		&i.PrevRunID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.ToolName,
		&i.ToolVersion,
		&i.VcsOrigin,
		&i.VcsBranch,
		&i.VcsCommit,
		&i.Scanners,
		&i.ScopeHash,
		&i.Counts,
		&i.Delta,
		&i.Unreadable,
		&i.Problem,
		&i.Document,
		&i.SyncedAt,
	)
	return i, err
}

const insertFinding = `-- name: InsertFinding :exec
INSERT INTO findings (
    org_id, repo_id, run_id, fingerprint, scanner, scanners, rule_id, aliases,
    category, severity, title, message, location_path, location_start_line,
    location_end_line, location_snippet, package_name, package_version,
    package_ecosystem, package_purl, fixed_in, refs, status
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17,
    $18, $19, $20, $21, $22, $23
)
`

type InsertFindingParams struct {
	OrgID             pgtype.UUID `json:"org_id"`
	RepoID            pgtype.UUID `json:"repo_id"`
	RunID             pgtype.UUID `json:"run_id"`
	Fingerprint       string      `json:"fingerprint"`
	Scanner           string      `json:"scanner"`
	Scanners          []byte      `json:"scanners"`
	RuleID            string      `json:"rule_id"`
	Aliases           []byte      `json:"aliases"`
	Category          string      `json:"category"`
	Severity          string      `json:"severity"`
	Title             string      `json:"title"`
	Message           string      `json:"message"`
	LocationPath      string      `json:"location_path"`
	LocationStartLine int32       `json:"location_start_line"`
	LocationEndLine   int32       `json:"location_end_line"`
	LocationSnippet   string      `json:"location_snippet"`
	PackageName       string      `json:"package_name"`
	PackageVersion    string      `json:"package_version"`
	PackageEcosystem  string      `json:"package_ecosystem"`
	PackagePurl       string      `json:"package_purl"`
	FixedIn           string      `json:"fixed_in"`
	Refs              []byte      `json:"refs"`
	Status            string      `json:"status"`
}

func (q *Queries) InsertFinding(ctx context.Context, arg InsertFindingParams) error {
	_, err := q.db.Exec(ctx, insertFinding,
		arg.OrgID,
		arg.RepoID,
		arg.RunID,
		arg.Fingerprint,
		arg.Scanner,
		arg.Scanners,
		arg.RuleID,
		arg.Aliases,
		arg.Category,
		arg.Severity,
		arg.Title,
		arg.Message,
		arg.LocationPath,
		arg.LocationStartLine,
		arg.LocationEndLine,
		arg.LocationSnippet,
		arg.PackageName,
		arg.PackageVersion,
		arg.PackageEcosystem,
		arg.PackagePurl,
		arg.FixedIn,
		arg.Refs,
		arg.Status,
	)
	return err
}

const insertFindingState = `-- name: InsertFindingState :exec
INSERT INTO finding_states (
    org_id, repo_id, fingerprint, status, severity, category, title, scanners,
    first_seen_at, last_seen_at, first_run, last_run, fixed_at, fixed_run,
    occurrences, regressions
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
`

type InsertFindingStateParams struct {
	OrgID       pgtype.UUID        `json:"org_id"`
	RepoID      pgtype.UUID        `json:"repo_id"`
	Fingerprint string             `json:"fingerprint"`
	Status      string             `json:"status"`
	Severity    string             `json:"severity"`
	Category    string             `json:"category"`
	Title       string             `json:"title"`
	Scanners    []byte             `json:"scanners"`
	FirstSeenAt pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	FirstRun    string             `json:"first_run"`
	LastRun     string             `json:"last_run"`
	FixedAt     pgtype.Timestamptz `json:"fixed_at"`
	FixedRun    string             `json:"fixed_run"`
	Occurrences int32              `json:"occurrences"`
	Regressions int32              `json:"regressions"`
}

func (q *Queries) InsertFindingState(ctx context.Context, arg InsertFindingStateParams) error {
	_, err := q.db.Exec(ctx, insertFindingState,
		arg.OrgID,
		arg.RepoID,
		arg.Fingerprint,
		arg.Status,
		arg.Severity,
		arg.Category,
		arg.Title,
		arg.Scanners,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.FirstRun,
		arg.LastRun,
		arg.FixedAt,
		arg.FixedRun,
		arg.Occurrences,
		arg.Regressions,
	)
	return err
}

const insertRepo = `-- name: InsertRepo :one
INSERT INTO repos (org_id, name, origin, last_run_id, first_synced_at, last_synced_at)
VALUES ($1, $2, $3, $4, now(), now())
RETURNING id, org_id, name, origin, last_run_id, first_synced_at, last_synced_at, created_at
`

type InsertRepoParams struct {
	OrgID     pgtype.UUID `json:"org_id"`
	Name      string      `json:"name"`
	Origin    string      `json:"origin"`
	LastRunID string      `json:"last_run_id"`
}

func (q *Queries) InsertRepo(ctx context.Context, arg InsertRepoParams) (Repo, error) {
	row := q.db.QueryRow(ctx, insertRepo,
		arg.OrgID,
		arg.Name,
		arg.Origin,
		arg.LastRunID,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Origin,
		&i.LastRunID,
		&i.FirstSyncedAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listFindingStatesByRepo = `-- name: ListFindingStatesByRepo :many
SELECT org_id, repo_id, fingerprint, status, severity, category, title, scanners,
       first_seen_at, last_seen_at, first_run, last_run, fixed_at, fixed_run,
       occurrences, regressions
FROM finding_states
WHERE org_id = $1 AND repo_id = $2
ORDER BY last_seen_at DESC
`

type ListFindingStatesByRepoParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	RepoID pgtype.UUID `json:"repo_id"`
}

func (q *Queries) ListFindingStatesByRepo(ctx context.Context, arg ListFindingStatesByRepoParams) ([]FindingState, error) {
	rows, err := q.db.Query(ctx, listFindingStatesByRepo, arg.OrgID, arg.RepoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindingState{}
	for rows.Next() {
		var i FindingState
		if err := rows.Scan(
			&i.OrgID,
			&i.RepoID,
			&i.Fingerprint,
			&i.Status,
			&i.Severity,
			&i.Category,
			&i.Title,
			&i.Scanners,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.FirstRun,
			&i.LastRun,
			&i.FixedAt,
			&i.FixedRun,
			&i.Occurrences,
			&i.Regressions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsByRunFiltered = `-- name: ListFindingsByRunFiltered :many
SELECT
    f.id, f.org_id, f.repo_id, f.run_id, f.fingerprint, f.scanner, f.scanners, f.rule_id, f.aliases,
    f.category, f.severity, f.title, f.message, f.location_path, f.location_start_line,
    f.location_end_line, f.location_snippet, f.package_name, f.package_version,
    f.package_ecosystem, f.package_purl, f.fixed_in, f.refs, f.status,
    fs.first_seen_at
FROM findings f
LEFT JOIN finding_states fs
    ON fs.org_id = f.org_id AND fs.repo_id = f.repo_id AND fs.fingerprint = f.fingerprint
WHERE f.org_id = $1 AND f.run_id = $2
  AND ($3 = '' OR f.severity = $3)
  AND ($4 = '' OR f.category = $4)
  AND ($5 = '' OR f.status = $5)
  AND ($6 = '' OR (
    f.title ILIKE '%' || $6 || '%'
    OR f.message ILIKE '%' || $6 || '%'
    OR f.rule_id ILIKE '%' || $6 || '%'
    OR f.location_path ILIKE '%' || $6 || '%'
  ))
ORDER BY
    CASE f.severity
        WHEN 'critical' THEN 5
        WHEN 'high' THEN 4
        WHEN 'medium' THEN 3
        WHEN 'low' THEN 2
        WHEN 'info' THEN 1
        ELSE 0
    END DESC,
    f.fingerprint
LIMIT $8 OFFSET $7
`

type ListFindingsByRunFilteredParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	RunID      pgtype.UUID `json:"run_id"`
	Severity   interface{} `json:"severity"`
	Category   interface{} `json:"category"`
	Status     interface{} `json:"status"`
	Search     interface{} `json:"search"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

type ListFindingsByRunFilteredRow struct {
	ID                int64              `json:"id"`
	OrgID             pgtype.UUID        `json:"org_id"`
	RepoID            pgtype.UUID        `json:"repo_id"`
	RunID             pgtype.UUID        `json:"run_id"`
	Fingerprint       string             `json:"fingerprint"`
	Scanner           string             `json:"scanner"`
	Scanners          []byte             `json:"scanners"`
	RuleID            string             `json:"rule_id"`
	Aliases           []byte             `json:"aliases"`
	Category          string             `json:"category"`
	Severity          string             `json:"severity"`
	Title             string             `json:"title"`
	Message           string             `json:"message"`
	LocationPath      string             `json:"location_path"`
	LocationStartLine int32              `json:"location_start_line"`
	LocationEndLine   int32              `json:"location_end_line"`
	LocationSnippet   string             `json:"location_snippet"`
	PackageName       string             `json:"package_name"`
	PackageVersion    string             `json:"package_version"`
	PackageEcosystem  string             `json:"package_ecosystem"`
	PackagePurl       string             `json:"package_purl"`
	FixedIn           string             `json:"fixed_in"`
	Refs              []byte             `json:"refs"`
	Status            string             `json:"status"`
	FirstSeenAt       pgtype.Timestamptz `json:"first_seen_at"`
}

func (q *Queries) ListFindingsByRunFiltered(ctx context.Context, arg ListFindingsByRunFilteredParams) ([]ListFindingsByRunFilteredRow, error) {
	rows, err := q.db.Query(ctx, listFindingsByRunFiltered,
		arg.OrgID,
		arg.RunID,
		arg.Severity,
		arg.Category,
		arg.Status,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFindingsByRunFilteredRow{}
	for rows.Next() {
		var i ListFindingsByRunFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RepoID,
			&i.RunID,
			&i.Fingerprint,
			&i.Scanner,
			&i.Scanners,
			&i.RuleID,
			&i.Aliases,
			&i.Category,
			&i.Severity,
			&i.Title,
			&i.Message,
			&i.LocationPath,
			&i.LocationStartLine,
			&i.LocationEndLine,
			&i.LocationSnippet,
			&i.PackageName,
			&i.PackageVersion,
			&i.PackageEcosystem,
			&i.PackagePurl,
			&i.FixedIn,
			&i.Refs,
			&i.Status,
			&i.FirstSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoLinksByOrg = `-- name: ListRepoLinksByOrg :many
SELECT id, org_id, repo_id, source, external_id, path, former_paths, metadata,
       first_synced_at, last_synced_at
FROM repo_links
WHERE org_id = $1
ORDER BY last_synced_at DESC
`

func (q *Queries) ListRepoLinksByOrg(ctx context.Context, orgID pgtype.UUID) ([]RepoLink, error) {
	rows, err := q.db.Query(ctx, listRepoLinksByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RepoLink{}
	for rows.Next() {
		var i RepoLink
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RepoID,
			&i.Source,
			&i.ExternalID,
			&i.Path,
			&i.FormerPaths,
			&i.Metadata,
			&i.FirstSyncedAt,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoLinksByRepo = `-- name: ListRepoLinksByRepo :many
SELECT id, org_id, repo_id, source, external_id, path, former_paths, metadata,
       first_synced_at, last_synced_at
FROM repo_links
WHERE org_id = $1 AND repo_id = $2
ORDER BY last_synced_at DESC
`

type ListRepoLinksByRepoParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	RepoID pgtype.UUID `json:"repo_id"`
}

func (q *Queries) ListRepoLinksByRepo(ctx context.Context, arg ListRepoLinksByRepoParams) ([]RepoLink, error) {
	rows, err := q.db.Query(ctx, listRepoLinksByRepo, arg.OrgID, arg.RepoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RepoLink{}
	for rows.Next() {
		var i RepoLink
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RepoID,
			&i.Source,
			&i.ExternalID,
			&i.Path,
			&i.FormerPaths,
			&i.Metadata,
			&i.FirstSyncedAt,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposByOrg = `-- name: ListReposByOrg :many
SELECT id, org_id, name, origin, last_run_id, first_synced_at, last_synced_at, created_at
FROM repos
WHERE org_id = $1
ORDER BY last_synced_at DESC
`

func (q *Queries) ListReposByOrg(ctx context.Context, orgID pgtype.UUID) ([]Repo, error) {
	rows, err := q.db.Query(ctx, listReposByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repo{}
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Origin,
			&i.LastRunID,
			&i.FirstSyncedAt,
			&i.LastSyncedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByRepo = `-- name: ListRunsByRepo :many
SELECT id, org_id, repo_id, source, client_run_id, prev_run_id, started_at, finished_at,
       duration_ms, tool_name, tool_version, vcs_origin, vcs_branch, vcs_commit,
       scanners, scope_hash, counts, delta, unreadable, problem, document, synced_at
FROM runs
WHERE org_id = $1 AND repo_id = $2
ORDER BY finished_at DESC
`

type ListRunsByRepoParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	RepoID pgtype.UUID `json:"repo_id"`
}

func (q *Queries) ListRunsByRepo(ctx context.Context, arg ListRunsByRepoParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRunsByRepo, arg.OrgID, arg.RepoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RepoID,
			&i.Source,
			&i.ClientRunID,
			&i.PrevRunID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ToolName,
			&i.ToolVersion,
			&i.VcsOrigin,
			&i.VcsBranch,
			&i.VcsCommit,
			&i.Scanners,
			&i.ScopeHash,
			&i.Counts,
			&i.Delta,
			&i.Unreadable,
			&i.Problem,
			&i.Document,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchRepoLastRun = `-- name: TouchRepoLastRun :exec
UPDATE repos
SET last_run_id = $3,
    last_synced_at = now()
WHERE org_id = $1 AND id = $2
`

type TouchRepoLastRunParams struct {
	OrgID     pgtype.UUID `json:"org_id"`
	ID        pgtype.UUID `json:"id"`
	LastRunID string      `json:"last_run_id"`
}

func (q *Queries) TouchRepoLastRun(ctx context.Context, arg TouchRepoLastRunParams) error {
	_, err := q.db.Exec(ctx, touchRepoLastRun, arg.OrgID, arg.ID, arg.LastRunID)
	return err
}

const updateRepoSynced = `-- name: UpdateRepoSynced :exec
UPDATE repos
SET name = $3,
    origin = $4,
    last_run_id = $5,
    last_synced_at = now()
WHERE org_id = $1 AND id = $2
`

type UpdateRepoSyncedParams struct {
	OrgID     pgtype.UUID `json:"org_id"`
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	Origin    string      `json:"origin"`
	LastRunID string      `json:"last_run_id"`
}

func (q *Queries) UpdateRepoSynced(ctx context.Context, arg UpdateRepoSyncedParams) error {
	_, err := q.db.Exec(ctx, updateRepoSynced,
		arg.OrgID,
		arg.ID,
		arg.Name,
		arg.Origin,
		arg.LastRunID,
	)
	return err
}

const upsertRepoLink = `-- name: UpsertRepoLink :one
INSERT INTO repo_links (
    org_id, repo_id, source, external_id, path, former_paths, metadata,
    first_synced_at, last_synced_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, now(), now())
ON CONFLICT (org_id, source, external_id) DO UPDATE SET
    repo_id = EXCLUDED.repo_id,
    path = EXCLUDED.path,
    former_paths = EXCLUDED.former_paths,
    metadata = EXCLUDED.metadata,
    last_synced_at = now()
RETURNING id, org_id, repo_id, source, external_id, path, former_paths, metadata,
          first_synced_at, last_synced_at
`

type UpsertRepoLinkParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	RepoID      pgtype.UUID `json:"repo_id"`
	Source      string      `json:"source"`
	ExternalID  string      `json:"external_id"`
	Path        string      `json:"path"`
	FormerPaths []byte      `json:"former_paths"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) UpsertRepoLink(ctx context.Context, arg UpsertRepoLinkParams) (RepoLink, error) {
	row := q.db.QueryRow(ctx, upsertRepoLink,
		arg.OrgID,
		arg.RepoID,
		arg.Source,
		arg.ExternalID,
		arg.Path,
		arg.FormerPaths,
		arg.Metadata,
	)
	var i RepoLink
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RepoID,
		&i.Source,
		&i.ExternalID,
		&i.Path,
		&i.FormerPaths,
		&i.Metadata,
		&i.FirstSyncedAt,
		&i.LastSyncedAt,
	)
	return i, err
}

const upsertRun = `-- name: UpsertRun :one
INSERT INTO runs (
    org_id, repo_id, source, client_run_id, prev_run_id, started_at, finished_at,
    duration_ms, tool_name, tool_version, vcs_origin, vcs_branch, vcs_commit,
    scanners, scope_hash, counts, delta, unreadable, problem, document, synced_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17,
    $18, $19, $20, now()
)
ON CONFLICT (repo_id, client_run_id) DO UPDATE SET
    source = EXCLUDED.source,
    prev_run_id = EXCLUDED.prev_run_id,
    started_at = EXCLUDED.started_at,
    finished_at = EXCLUDED.finished_at,
    duration_ms = EXCLUDED.duration_ms,
    tool_name = EXCLUDED.tool_name,
    tool_version = EXCLUDED.tool_version,
    vcs_origin = EXCLUDED.vcs_origin,
    vcs_branch = EXCLUDED.vcs_branch,
    vcs_commit = EXCLUDED.vcs_commit,
    scanners = EXCLUDED.scanners,
    scope_hash = EXCLUDED.scope_hash,
    counts = EXCLUDED.counts,
    delta = EXCLUDED.delta,
    unreadable = EXCLUDED.unreadable,
    problem = EXCLUDED.problem,
    document = EXCLUDED.document,
    synced_at = now()
RETURNING id, org_id, repo_id, source, client_run_id, prev_run_id, started_at, finished_at,
          duration_ms, tool_name, tool_version, vcs_origin, vcs_branch, vcs_commit,
          scanners, scope_hash, counts, delta, unreadable, problem, document, synced_at
`

type UpsertRunParams struct {
	OrgID       pgtype.UUID        `json:"org_id"`
	RepoID      pgtype.UUID        `json:"repo_id"`
	Source      string             `json:"source"`
	ClientRunID string             `json:"client_run_id"`
	PrevRunID   string             `json:"prev_run_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	DurationMs  int64              `json:"duration_ms"`
	ToolName    string             `json:"tool_name"`
	ToolVersion string             `json:"tool_version"`
	VcsOrigin   string             `json:"vcs_origin"`
	VcsBranch   string             `json:"vcs_branch"`
	VcsCommit   string             `json:"vcs_commit"`
	Scanners    []byte             `json:"scanners"`
	ScopeHash   string             `json:"scope_hash"`
	Counts      []byte             `json:"counts"`
	Delta       []byte             `json:"delta"`
	Unreadable  bool               `json:"unreadable"`
	Problem     string             `json:"problem"`
	Document    []byte             `json:"document"`
}

func (q *Queries) UpsertRun(ctx context.Context, arg UpsertRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, upsertRun,
		arg.OrgID,
		arg.RepoID,
		arg.Source,
		arg.ClientRunID,
		arg.PrevRunID,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationMs,
		arg.ToolName,
		arg.ToolVersion,
		arg.VcsOrigin,
		arg.VcsBranch,
		arg.VcsCommit,
		arg.Scanners,
		arg.ScopeHash,
		arg.Counts,
		arg.Delta,
		arg.Unreadable,
		arg.Problem,
		arg.Document,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RepoID,
		&i.Source,
		&i.ClientRunID,
		&i.PrevRunID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.ToolName,
		&i.ToolVersion,
		&i.VcsOrigin,
		&i.VcsBranch,
		&i.VcsCommit,
		&i.Scanners,
		&i.ScopeHash,
		&i.Counts,
		&i.Delta,
		&i.Unreadable,
		&i.Problem,
		&i.Document,
		&i.SyncedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (id, email)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email
`

type UpsertUserParams struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.Exec(ctx, upsertUser, arg.ID, arg.Email)
	return err
}
