import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { createRouter, RouterProvider } from '@tanstack/react-router'
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'

import { AuthProvider } from '@/lib/auth'
import { primeInitialSession } from '@/lib/auth-bootstrap'
import { isCloudMode, loadAppConfig } from '@/lib/config'
import './index.css'
// Generated by @tanstack/router-plugin from src/routes on every build.
import { routeTree } from './routeTree.gen'

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      // The report is a local file that only changes when someone re-runs a
      // scan, so aggressive refetching would only add noise.
      staleTime: 30_000,
      refetchOnWindowFocus: false,
      // A missing report is a setup state, not a transient fault; retrying
      // just delays showing the user what to do about it.
      retry: false,
    },
  },
})

const router = createRouter({ routeTree })

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

const rootElement = document.getElementById('root')
if (!rootElement) {
  throw new Error('root element not found')
}
const root = rootElement

async function bootstrap() {
  try {
    await loadAppConfig()
    if (isCloudMode()) {
      primeInitialSession()
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Failed to load configuration'
    root.textContent = message
    return
  }

  createRoot(root).render(
    <StrictMode>
      <QueryClientProvider client={queryClient}>
        <AuthProvider>
          <RouterProvider router={router} />
        </AuthProvider>
      </QueryClientProvider>
    </StrictMode>,
  )
}

void bootstrap()
